[package]
name = "generate_world_collisions"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_ecs_ldtk = "0.10.0"
bevy_rapier2d = "0.27.0"
bevy_prototype_lyon = "0.12.0"
rand = "0.8.5"
