pub mod events;

use bevy::prelude::*;
use bevy_asset_loader::prelude::*;
use bevy_ecs_ldtk::prelude::LdtkProject;
use bevy_trickfilm::prelude::*;

// TODO: Write test that makes sure size equals this?
pub const PLAYER_SPRITE_SIZE: u32 = 125;

pub struct AssetPlugin;

impl Plugin for AssetPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(events::AssetEventsPlugin);
    }
}

#[derive(AssetCollection, Resource)]
pub struct GameAssets {
    #[asset(path = "attack/arc.png")]
    pub attack_arc: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 6, rows = 1))]
    pub attack_arc_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#arc")]
    pub attack_arc_animation: Handle<AnimationClip2D>,

    #[asset(path = "attack/vertical_line.png")]
    pub attack_vertical_line: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 6, rows = 1))]
    pub attack_vertical_line_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#vertical_line")]
    pub attack_vertical_line_animation: Handle<AnimationClip2D>,

    #[asset(path = "attack/half_circle.png")]
    pub attack_half_circle: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 6, rows = 1))]
    pub attack_half_circle_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#half_circle")]
    pub attack_half_circle_animation: Handle<AnimationClip2D>,

    #[asset(path = "attack/flat_line.png")]
    pub attack_flat_line: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 5, rows = 1))]
    pub attack_flat_line_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#flat_line")]
    pub attack_flat_line_animation: Handle<AnimationClip2D>,

    #[asset(
        paths(
            "dude/idle.png",
            "dude/run.png",
            "dude/jab.png",
            "dude/jab_recover.png",
            "dude/punch.png",
            "dude/punch_recover.png",
            "dude/left_hook.png",
            "dude/left_hook_recover.png",
            "dude/stagger.png",
            "dude/stagger_recover.png",
            "dude/front_kick.png",
            "dude/front_kick_recover.png",
            "dude/spinning_back_kick.png",
            "dude/spinning_back_kick_recover.png",
            "dude/axe_kick.png",
            "dude/axe_kick_recover.png",
            "dude/stance_broken.png",
            "dude/stance_broken_recover.png",
            "dude/parry.png",
            "dude/parry_fail.png",
            "dude/parry_success.png",
            "dude/dash.png",
            "dude/fall.png",
            "dude/fall_recover.png",
            "dude/dropkick.png",
            "dude/dropkick_recover.png",
            "dude/hammer_fist.png",
            "dude/hammer_fist_recover.png",
        ),
        collection(typed)
    )]
    pub dude_textures: Vec<Handle<Image>>,
    #[asset(path = "dude/shadow.png")]
    pub dude_shadow: Handle<Image>,

    #[asset(texture_atlas_layout(tile_size_x = 125, tile_size_y = 125, columns = 19, rows = 8))]
    pub dude_layout: Handle<TextureAtlasLayout>,
    #[asset(
        paths(
            "dude/dude.trickfilm.ron#idle-o0",
            "dude/dude.trickfilm.ron#idle-o1",
            "dude/dude.trickfilm.ron#idle-o2",
            "dude/dude.trickfilm.ron#idle-o3",
            "dude/dude.trickfilm.ron#idle-o4",
            "dude/dude.trickfilm.ron#idle-o5",
            "dude/dude.trickfilm.ron#idle-o6",
            "dude/dude.trickfilm.ron#idle-o7",
            "dude/dude.trickfilm.ron#run-o0",
            "dude/dude.trickfilm.ron#run-o1",
            "dude/dude.trickfilm.ron#run-o2",
            "dude/dude.trickfilm.ron#run-o3",
            "dude/dude.trickfilm.ron#run-o4",
            "dude/dude.trickfilm.ron#run-o5",
            "dude/dude.trickfilm.ron#run-o6",
            "dude/dude.trickfilm.ron#run-o7",
            "dude/dude.trickfilm.ron#jab-o0",
            "dude/dude.trickfilm.ron#jab-o1",
            "dude/dude.trickfilm.ron#jab-o2",
            "dude/dude.trickfilm.ron#jab-o3",
            "dude/dude.trickfilm.ron#jab-o4",
            "dude/dude.trickfilm.ron#jab-o5",
            "dude/dude.trickfilm.ron#jab-o6",
            "dude/dude.trickfilm.ron#jab-o7",
            "dude/dude.trickfilm.ron#jab_recover-o0",
            "dude/dude.trickfilm.ron#jab_recover-o1",
            "dude/dude.trickfilm.ron#jab_recover-o2",
            "dude/dude.trickfilm.ron#jab_recover-o3",
            "dude/dude.trickfilm.ron#jab_recover-o4",
            "dude/dude.trickfilm.ron#jab_recover-o5",
            "dude/dude.trickfilm.ron#jab_recover-o6",
            "dude/dude.trickfilm.ron#jab_recover-o7",
            "dude/dude.trickfilm.ron#punch-o0",
            "dude/dude.trickfilm.ron#punch-o1",
            "dude/dude.trickfilm.ron#punch-o2",
            "dude/dude.trickfilm.ron#punch-o3",
            "dude/dude.trickfilm.ron#punch-o4",
            "dude/dude.trickfilm.ron#punch-o5",
            "dude/dude.trickfilm.ron#punch-o6",
            "dude/dude.trickfilm.ron#punch-o7",
            "dude/dude.trickfilm.ron#punch_recover-o0",
            "dude/dude.trickfilm.ron#punch_recover-o1",
            "dude/dude.trickfilm.ron#punch_recover-o2",
            "dude/dude.trickfilm.ron#punch_recover-o3",
            "dude/dude.trickfilm.ron#punch_recover-o4",
            "dude/dude.trickfilm.ron#punch_recover-o5",
            "dude/dude.trickfilm.ron#punch_recover-o6",
            "dude/dude.trickfilm.ron#punch_recover-o7",
            "dude/dude.trickfilm.ron#left_hook-o0",
            "dude/dude.trickfilm.ron#left_hook-o1",
            "dude/dude.trickfilm.ron#left_hook-o2",
            "dude/dude.trickfilm.ron#left_hook-o3",
            "dude/dude.trickfilm.ron#left_hook-o4",
            "dude/dude.trickfilm.ron#left_hook-o5",
            "dude/dude.trickfilm.ron#left_hook-o6",
            "dude/dude.trickfilm.ron#left_hook-o7",
            "dude/dude.trickfilm.ron#left_hook_recover-o0",
            "dude/dude.trickfilm.ron#left_hook_recover-o1",
            "dude/dude.trickfilm.ron#left_hook_recover-o2",
            "dude/dude.trickfilm.ron#left_hook_recover-o3",
            "dude/dude.trickfilm.ron#left_hook_recover-o4",
            "dude/dude.trickfilm.ron#left_hook_recover-o5",
            "dude/dude.trickfilm.ron#left_hook_recover-o6",
            "dude/dude.trickfilm.ron#left_hook_recover-o7",
            "dude/dude.trickfilm.ron#stagger-o0",
            "dude/dude.trickfilm.ron#stagger-o1",
            "dude/dude.trickfilm.ron#stagger-o2",
            "dude/dude.trickfilm.ron#stagger-o3",
            "dude/dude.trickfilm.ron#stagger-o4",
            "dude/dude.trickfilm.ron#stagger-o5",
            "dude/dude.trickfilm.ron#stagger-o6",
            "dude/dude.trickfilm.ron#stagger-o7",
            "dude/dude.trickfilm.ron#stagger_recover-o0",
            "dude/dude.trickfilm.ron#stagger_recover-o1",
            "dude/dude.trickfilm.ron#stagger_recover-o2",
            "dude/dude.trickfilm.ron#stagger_recover-o3",
            "dude/dude.trickfilm.ron#stagger_recover-o4",
            "dude/dude.trickfilm.ron#stagger_recover-o5",
            "dude/dude.trickfilm.ron#stagger_recover-o6",
            "dude/dude.trickfilm.ron#stagger_recover-o7",
            "dude/dude.trickfilm.ron#front_kick-o0",
            "dude/dude.trickfilm.ron#front_kick-o1",
            "dude/dude.trickfilm.ron#front_kick-o2",
            "dude/dude.trickfilm.ron#front_kick-o3",
            "dude/dude.trickfilm.ron#front_kick-o4",
            "dude/dude.trickfilm.ron#front_kick-o5",
            "dude/dude.trickfilm.ron#front_kick-o6",
            "dude/dude.trickfilm.ron#front_kick-o7",
            "dude/dude.trickfilm.ron#front_kick_recover-o0",
            "dude/dude.trickfilm.ron#front_kick_recover-o1",
            "dude/dude.trickfilm.ron#front_kick_recover-o2",
            "dude/dude.trickfilm.ron#front_kick_recover-o3",
            "dude/dude.trickfilm.ron#front_kick_recover-o4",
            "dude/dude.trickfilm.ron#front_kick_recover-o5",
            "dude/dude.trickfilm.ron#front_kick_recover-o6",
            "dude/dude.trickfilm.ron#front_kick_recover-o7",
            "dude/dude.trickfilm.ron#spinning_back_kick-o0",
            "dude/dude.trickfilm.ron#spinning_back_kick-o1",
            "dude/dude.trickfilm.ron#spinning_back_kick-o2",
            "dude/dude.trickfilm.ron#spinning_back_kick-o3",
            "dude/dude.trickfilm.ron#spinning_back_kick-o4",
            "dude/dude.trickfilm.ron#spinning_back_kick-o5",
            "dude/dude.trickfilm.ron#spinning_back_kick-o6",
            "dude/dude.trickfilm.ron#spinning_back_kick-o7",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o0",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o1",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o2",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o3",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o4",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o5",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o6",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o7",
            "dude/dude.trickfilm.ron#axe_kick-o0",
            "dude/dude.trickfilm.ron#axe_kick-o1",
            "dude/dude.trickfilm.ron#axe_kick-o2",
            "dude/dude.trickfilm.ron#axe_kick-o3",
            "dude/dude.trickfilm.ron#axe_kick-o4",
            "dude/dude.trickfilm.ron#axe_kick-o5",
            "dude/dude.trickfilm.ron#axe_kick-o6",
            "dude/dude.trickfilm.ron#axe_kick-o7",
            "dude/dude.trickfilm.ron#axe_kick_recover-o0",
            "dude/dude.trickfilm.ron#axe_kick_recover-o1",
            "dude/dude.trickfilm.ron#axe_kick_recover-o2",
            "dude/dude.trickfilm.ron#axe_kick_recover-o3",
            "dude/dude.trickfilm.ron#axe_kick_recover-o4",
            "dude/dude.trickfilm.ron#axe_kick_recover-o5",
            "dude/dude.trickfilm.ron#axe_kick_recover-o6",
            "dude/dude.trickfilm.ron#axe_kick_recover-o7",
            "dude/dude.trickfilm.ron#stance_broken-o0",
            "dude/dude.trickfilm.ron#stance_broken-o1",
            "dude/dude.trickfilm.ron#stance_broken-o2",
            "dude/dude.trickfilm.ron#stance_broken-o3",
            "dude/dude.trickfilm.ron#stance_broken-o4",
            "dude/dude.trickfilm.ron#stance_broken-o5",
            "dude/dude.trickfilm.ron#stance_broken-o6",
            "dude/dude.trickfilm.ron#stance_broken-o7",
            "dude/dude.trickfilm.ron#stance_broken_recover-o0",
            "dude/dude.trickfilm.ron#stance_broken_recover-o1",
            "dude/dude.trickfilm.ron#stance_broken_recover-o2",
            "dude/dude.trickfilm.ron#stance_broken_recover-o3",
            "dude/dude.trickfilm.ron#stance_broken_recover-o4",
            "dude/dude.trickfilm.ron#stance_broken_recover-o5",
            "dude/dude.trickfilm.ron#stance_broken_recover-o6",
            "dude/dude.trickfilm.ron#stance_broken_recover-o7",
            "dude/dude.trickfilm.ron#parry-o0",
            "dude/dude.trickfilm.ron#parry-o1",
            "dude/dude.trickfilm.ron#parry-o2",
            "dude/dude.trickfilm.ron#parry-o3",
            "dude/dude.trickfilm.ron#parry-o4",
            "dude/dude.trickfilm.ron#parry-o5",
            "dude/dude.trickfilm.ron#parry-o6",
            "dude/dude.trickfilm.ron#parry-o7",
            "dude/dude.trickfilm.ron#parry_fail-o0",
            "dude/dude.trickfilm.ron#parry_fail-o1",
            "dude/dude.trickfilm.ron#parry_fail-o2",
            "dude/dude.trickfilm.ron#parry_fail-o3",
            "dude/dude.trickfilm.ron#parry_fail-o4",
            "dude/dude.trickfilm.ron#parry_fail-o5",
            "dude/dude.trickfilm.ron#parry_fail-o6",
            "dude/dude.trickfilm.ron#parry_fail-o7",
            "dude/dude.trickfilm.ron#parry_success-o0",
            "dude/dude.trickfilm.ron#parry_success-o1",
            "dude/dude.trickfilm.ron#parry_success-o2",
            "dude/dude.trickfilm.ron#parry_success-o3",
            "dude/dude.trickfilm.ron#parry_success-o4",
            "dude/dude.trickfilm.ron#parry_success-o5",
            "dude/dude.trickfilm.ron#parry_success-o6",
            "dude/dude.trickfilm.ron#parry_success-o7",
            "dude/dude.trickfilm.ron#dash-o0",
            "dude/dude.trickfilm.ron#dash-o1",
            "dude/dude.trickfilm.ron#dash-o2",
            "dude/dude.trickfilm.ron#dash-o3",
            "dude/dude.trickfilm.ron#dash-o4",
            "dude/dude.trickfilm.ron#dash-o5",
            "dude/dude.trickfilm.ron#dash-o6",
            "dude/dude.trickfilm.ron#dash-o7",
            "dude/dude.trickfilm.ron#fall-o0",
            "dude/dude.trickfilm.ron#fall-o1",
            "dude/dude.trickfilm.ron#fall-o2",
            "dude/dude.trickfilm.ron#fall-o3",
            "dude/dude.trickfilm.ron#fall-o4",
            "dude/dude.trickfilm.ron#fall-o5",
            "dude/dude.trickfilm.ron#fall-o6",
            "dude/dude.trickfilm.ron#fall-o7",
            "dude/dude.trickfilm.ron#fall_recover-o0",
            "dude/dude.trickfilm.ron#fall_recover-o1",
            "dude/dude.trickfilm.ron#fall_recover-o2",
            "dude/dude.trickfilm.ron#fall_recover-o3",
            "dude/dude.trickfilm.ron#fall_recover-o4",
            "dude/dude.trickfilm.ron#fall_recover-o5",
            "dude/dude.trickfilm.ron#fall_recover-o6",
            "dude/dude.trickfilm.ron#fall_recover-o7",
            "dude/dude.trickfilm.ron#dropkick-o0",
            "dude/dude.trickfilm.ron#dropkick-o1",
            "dude/dude.trickfilm.ron#dropkick-o2",
            "dude/dude.trickfilm.ron#dropkick-o3",
            "dude/dude.trickfilm.ron#dropkick-o4",
            "dude/dude.trickfilm.ron#dropkick-o5",
            "dude/dude.trickfilm.ron#dropkick-o6",
            "dude/dude.trickfilm.ron#dropkick-o7",
            "dude/dude.trickfilm.ron#dropkick_recover-o0",
            "dude/dude.trickfilm.ron#dropkick_recover-o1",
            "dude/dude.trickfilm.ron#dropkick_recover-o2",
            "dude/dude.trickfilm.ron#dropkick_recover-o3",
            "dude/dude.trickfilm.ron#dropkick_recover-o4",
            "dude/dude.trickfilm.ron#dropkick_recover-o5",
            "dude/dude.trickfilm.ron#dropkick_recover-o6",
            "dude/dude.trickfilm.ron#dropkick_recover-o7",
            "dude/dude.trickfilm.ron#hammer_fist-o0",
            "dude/dude.trickfilm.ron#hammer_fist-o1",
            "dude/dude.trickfilm.ron#hammer_fist-o2",
            "dude/dude.trickfilm.ron#hammer_fist-o3",
            "dude/dude.trickfilm.ron#hammer_fist-o4",
            "dude/dude.trickfilm.ron#hammer_fist-o5",
            "dude/dude.trickfilm.ron#hammer_fist-o6",
            "dude/dude.trickfilm.ron#hammer_fist-o7",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o0",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o1",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o2",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o3",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o4",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o5",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o6",
            "dude/dude.trickfilm.ron#hammer_fist_recover-o7",
        ),
        collection(typed)
    )]
    pub dude_animations: Vec<Handle<AnimationClip2D>>,

    #[asset(
        paths(
            "enemy/goon/idle.png",
            "enemy/goon/run.png",
            "enemy/goon/punch.png",
            "enemy/goon/punch_recover.png",
            "enemy/goon/spinning_back_kick.png",
            "enemy/goon/spinning_back_kick_recover.png",
            "enemy/goon/stagger.png",
            "enemy/goon/stagger_recover.png",
            "enemy/goon/stance_broken.png",
            "enemy/goon/stance_broken_recover.png",
            "enemy/goon/fall.png",
            "enemy/goon/fall_recover.png",
            "enemy/goon/stalking.png",
            "enemy/goon/stalking_forward.png",
            "enemy/goon/stalking_right.png",
            "enemy/goon/stalking_back.png",
            "enemy/goon/stalking_left.png",
        ),
        collection(typed)
    )]
    pub enemy_goon_textures: Vec<Handle<Image>>,
    #[asset(path = "dude/shadow.png")]
    pub enemy_goon_shadow: Handle<Image>,

    #[asset(texture_atlas_layout(tile_size_x = 125, tile_size_y = 125, columns = 21, rows = 8))]
    pub enemy_goon_layout: Handle<TextureAtlasLayout>,
    #[asset(
        paths(
            "enemy/goon/goon.trickfilm.ron#idle-o0",
            "enemy/goon/goon.trickfilm.ron#idle-o1",
            "enemy/goon/goon.trickfilm.ron#idle-o2",
            "enemy/goon/goon.trickfilm.ron#idle-o3",
            "enemy/goon/goon.trickfilm.ron#idle-o4",
            "enemy/goon/goon.trickfilm.ron#idle-o5",
            "enemy/goon/goon.trickfilm.ron#idle-o6",
            "enemy/goon/goon.trickfilm.ron#idle-o7",
            "enemy/goon/goon.trickfilm.ron#run-o0",
            "enemy/goon/goon.trickfilm.ron#run-o1",
            "enemy/goon/goon.trickfilm.ron#run-o2",
            "enemy/goon/goon.trickfilm.ron#run-o3",
            "enemy/goon/goon.trickfilm.ron#run-o4",
            "enemy/goon/goon.trickfilm.ron#run-o5",
            "enemy/goon/goon.trickfilm.ron#run-o6",
            "enemy/goon/goon.trickfilm.ron#run-o7",
            "enemy/goon/goon.trickfilm.ron#punch-o0",
            "enemy/goon/goon.trickfilm.ron#punch-o1",
            "enemy/goon/goon.trickfilm.ron#punch-o2",
            "enemy/goon/goon.trickfilm.ron#punch-o3",
            "enemy/goon/goon.trickfilm.ron#punch-o4",
            "enemy/goon/goon.trickfilm.ron#punch-o5",
            "enemy/goon/goon.trickfilm.ron#punch-o6",
            "enemy/goon/goon.trickfilm.ron#punch-o7",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o0",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o1",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o2",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o3",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o4",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o5",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o6",
            "enemy/goon/goon.trickfilm.ron#punch_recover-o7",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o0",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o1",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o2",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o3",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o4",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o5",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o6",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick-o7",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o0",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o1",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o2",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o3",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o4",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o5",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o6",
            "enemy/goon/goon.trickfilm.ron#spinning_back_kick_recover-o7",
            "enemy/goon/goon.trickfilm.ron#stagger-o0",
            "enemy/goon/goon.trickfilm.ron#stagger-o1",
            "enemy/goon/goon.trickfilm.ron#stagger-o2",
            "enemy/goon/goon.trickfilm.ron#stagger-o3",
            "enemy/goon/goon.trickfilm.ron#stagger-o4",
            "enemy/goon/goon.trickfilm.ron#stagger-o5",
            "enemy/goon/goon.trickfilm.ron#stagger-o6",
            "enemy/goon/goon.trickfilm.ron#stagger-o7",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o0",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o1",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o2",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o3",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o4",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o5",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o6",
            "enemy/goon/goon.trickfilm.ron#stagger_recover-o7",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o0",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o1",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o2",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o3",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o4",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o5",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o6",
            "enemy/goon/goon.trickfilm.ron#stance_broken-o7",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o0",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o1",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o2",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o3",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o4",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o5",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o6",
            "enemy/goon/goon.trickfilm.ron#stance_broken_recover-o7",
            "enemy/goon/goon.trickfilm.ron#fall-o0",
            "enemy/goon/goon.trickfilm.ron#fall-o1",
            "enemy/goon/goon.trickfilm.ron#fall-o2",
            "enemy/goon/goon.trickfilm.ron#fall-o3",
            "enemy/goon/goon.trickfilm.ron#fall-o4",
            "enemy/goon/goon.trickfilm.ron#fall-o5",
            "enemy/goon/goon.trickfilm.ron#fall-o6",
            "enemy/goon/goon.trickfilm.ron#fall-o7",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o0",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o1",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o2",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o3",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o4",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o5",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o6",
            "enemy/goon/goon.trickfilm.ron#fall_recover-o7",
            "enemy/goon/goon.trickfilm.ron#stalking-o0",
            "enemy/goon/goon.trickfilm.ron#stalking-o1",
            "enemy/goon/goon.trickfilm.ron#stalking-o2",
            "enemy/goon/goon.trickfilm.ron#stalking-o3",
            "enemy/goon/goon.trickfilm.ron#stalking-o4",
            "enemy/goon/goon.trickfilm.ron#stalking-o5",
            "enemy/goon/goon.trickfilm.ron#stalking-o6",
            "enemy/goon/goon.trickfilm.ron#stalking-o7",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o0",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o1",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o2",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o3",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o4",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o5",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o6",
            "enemy/goon/goon.trickfilm.ron#stalking_forward-o7",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o0",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o1",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o2",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o3",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o4",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o5",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o6",
            "enemy/goon/goon.trickfilm.ron#stalking_right-o7",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o0",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o1",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o2",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o3",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o4",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o5",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o6",
            "enemy/goon/goon.trickfilm.ron#stalking_back-o7",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o0",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o1",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o2",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o3",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o4",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o5",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o6",
            "enemy/goon/goon.trickfilm.ron#stalking_left-o7",
        ),
        collection(typed)
    )]
    pub enemy_goon_animations: Vec<Handle<AnimationClip2D>>,

    // --- MAP ---
    #[asset(path = "map/map.ldtk")]
    pub map: Handle<LdtkProject>,

    // --- FONTS ---
    #[asset(path = "fonts/PressStart2P.ttf")]
    pub pixel_font: Handle<Font>,
}
