pub mod events;

use bevy::prelude::*;
use bevy_asset_loader::prelude::*;
use bevy_ecs_ldtk::prelude::LdtkProject;
use bevy_trickfilm::prelude::*;

pub const PLAYER_SPRITE_SIZE: u32 = 100;

pub struct AssetPlugin;

impl Plugin for AssetPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(events::AssetEventsPlugin);
    }
}

#[derive(AssetCollection, Resource)]
pub struct GameAssets {
    #[asset(path = "attack/arc.png")]
    pub attack_arc: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 6, rows = 1))]
    pub attack_arc_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#arc")]
    pub attack_arc_animation: Handle<AnimationClip2D>,

    #[asset(path = "attack/vertical_line.png")]
    pub attack_vertical_line: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 6, rows = 1))]
    pub attack_vertical_line_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#vertical_line")]
    pub attack_vertical_line_animation: Handle<AnimationClip2D>,

    #[asset(path = "attack/half_circle.png")]
    pub attack_half_circle: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 6, rows = 1))]
    pub attack_half_circle_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#half_circle")]
    pub attack_half_circle_animation: Handle<AnimationClip2D>,

    #[asset(path = "attack/flat_line.png")]
    pub attack_flat_line: Handle<Image>,
    #[asset(texture_atlas_layout(tile_size_x = 64, tile_size_y = 64, columns = 5, rows = 1))]
    pub attack_flat_line_layout: Handle<TextureAtlasLayout>,
    #[asset(path = "attack/arc.trickfilm.ron#flat_line")]
    pub attack_flat_line_animation: Handle<AnimationClip2D>,

    #[asset(
        paths(
            "dude/dude_idle.png",
            "dude/dude_run.png",
            "dude/dude_jab.png",
            "dude/dude_jab_recover.png",
            "dude/dude_punch.png",
            "dude/dude_punch_recover.png",
            "dude/dude_front_kick.png",
            "dude/dude_front_kick_recover.png",
            "dude/dude_stagger.png",
            "dude/dude_stagger_recover.png",
            "dude/dude_axe_kick.png",
            "dude/dude_axe_kick_recover.png",
            "dude/dude_spinning_back_kick.png",
            "dude/dude_spinning_back_kick_recover.png",
            "dude/dude_spinning_heel_kick.png",
            "dude/dude_spinning_heel_kick_recover.png",
            "dude/dude_stance_broken.png",
            "dude/dude_stance_broken_recover.png",
            "dude/dude_parry.png",
            "dude/dude_parry_fail.png",
            "dude/dude_parry_success.png",
            "dude/dude_parry_success_recover.png",
            "dude/dude_slide.png",
            "dude/dude_slide_recover.png",
            "dude/dude_jump.png",
            "dude/dude_jump_recover_idle.png",
            "dude/dude_jump_recover_moving.png",
            "dude/dude_fall.png",
            "dude/dude_fall_recover.png",
            "dude/dude_dropkick.png",
            "dude/dude_dropkick_recover.png",
            "dude/dude_kneekick.png",
            "dude/dude_kneekick_recover.png",
        ),
        collection(typed)
    )]
    pub dude_textures: Vec<Handle<Image>>,
    #[asset(path = "dude/shadow.png")]
    pub dude_shadow: Handle<Image>,

    #[asset(texture_atlas_layout(tile_size_x = 100, tile_size_y = 100, columns = 19, rows = 8))]
    pub dude_layout: Handle<TextureAtlasLayout>,
    #[asset(
        paths(
            "dude/dude.trickfilm.ron#idle-o0",
            "dude/dude.trickfilm.ron#idle-o1",
            "dude/dude.trickfilm.ron#idle-o2",
            "dude/dude.trickfilm.ron#idle-o3",
            "dude/dude.trickfilm.ron#idle-o4",
            "dude/dude.trickfilm.ron#idle-o5",
            "dude/dude.trickfilm.ron#idle-o6",
            "dude/dude.trickfilm.ron#idle-o7",
            "dude/dude.trickfilm.ron#run-o0",
            "dude/dude.trickfilm.ron#run-o1",
            "dude/dude.trickfilm.ron#run-o2",
            "dude/dude.trickfilm.ron#run-o3",
            "dude/dude.trickfilm.ron#run-o4",
            "dude/dude.trickfilm.ron#run-o5",
            "dude/dude.trickfilm.ron#run-o6",
            "dude/dude.trickfilm.ron#run-o7",
            "dude/dude.trickfilm.ron#jab-o0",
            "dude/dude.trickfilm.ron#jab-o1",
            "dude/dude.trickfilm.ron#jab-o2",
            "dude/dude.trickfilm.ron#jab-o3",
            "dude/dude.trickfilm.ron#jab-o4",
            "dude/dude.trickfilm.ron#jab-o5",
            "dude/dude.trickfilm.ron#jab-o6",
            "dude/dude.trickfilm.ron#jab-o7",
            "dude/dude.trickfilm.ron#jab_recover-o0",
            "dude/dude.trickfilm.ron#jab_recover-o1",
            "dude/dude.trickfilm.ron#jab_recover-o2",
            "dude/dude.trickfilm.ron#jab_recover-o3",
            "dude/dude.trickfilm.ron#jab_recover-o4",
            "dude/dude.trickfilm.ron#jab_recover-o5",
            "dude/dude.trickfilm.ron#jab_recover-o6",
            "dude/dude.trickfilm.ron#jab_recover-o7",
            "dude/dude.trickfilm.ron#punch-o0",
            "dude/dude.trickfilm.ron#punch-o1",
            "dude/dude.trickfilm.ron#punch-o2",
            "dude/dude.trickfilm.ron#punch-o3",
            "dude/dude.trickfilm.ron#punch-o4",
            "dude/dude.trickfilm.ron#punch-o5",
            "dude/dude.trickfilm.ron#punch-o6",
            "dude/dude.trickfilm.ron#punch-o7",
            "dude/dude.trickfilm.ron#punch_recover-o0",
            "dude/dude.trickfilm.ron#punch_recover-o1",
            "dude/dude.trickfilm.ron#punch_recover-o2",
            "dude/dude.trickfilm.ron#punch_recover-o3",
            "dude/dude.trickfilm.ron#punch_recover-o4",
            "dude/dude.trickfilm.ron#punch_recover-o5",
            "dude/dude.trickfilm.ron#punch_recover-o6",
            "dude/dude.trickfilm.ron#punch_recover-o7",
            "dude/dude.trickfilm.ron#front_kick-o0",
            "dude/dude.trickfilm.ron#front_kick-o1",
            "dude/dude.trickfilm.ron#front_kick-o2",
            "dude/dude.trickfilm.ron#front_kick-o3",
            "dude/dude.trickfilm.ron#front_kick-o4",
            "dude/dude.trickfilm.ron#front_kick-o5",
            "dude/dude.trickfilm.ron#front_kick-o6",
            "dude/dude.trickfilm.ron#front_kick-o7",
            "dude/dude.trickfilm.ron#front_kick_recover-o0",
            "dude/dude.trickfilm.ron#front_kick_recover-o1",
            "dude/dude.trickfilm.ron#front_kick_recover-o2",
            "dude/dude.trickfilm.ron#front_kick_recover-o3",
            "dude/dude.trickfilm.ron#front_kick_recover-o4",
            "dude/dude.trickfilm.ron#front_kick_recover-o5",
            "dude/dude.trickfilm.ron#front_kick_recover-o6",
            "dude/dude.trickfilm.ron#front_kick_recover-o7",
            "dude/dude.trickfilm.ron#stagger-o0",
            "dude/dude.trickfilm.ron#stagger-o1",
            "dude/dude.trickfilm.ron#stagger-o2",
            "dude/dude.trickfilm.ron#stagger-o3",
            "dude/dude.trickfilm.ron#stagger-o4",
            "dude/dude.trickfilm.ron#stagger-o5",
            "dude/dude.trickfilm.ron#stagger-o6",
            "dude/dude.trickfilm.ron#stagger-o7",
            "dude/dude.trickfilm.ron#stagger_recover-o0",
            "dude/dude.trickfilm.ron#stagger_recover-o1",
            "dude/dude.trickfilm.ron#stagger_recover-o2",
            "dude/dude.trickfilm.ron#stagger_recover-o3",
            "dude/dude.trickfilm.ron#stagger_recover-o4",
            "dude/dude.trickfilm.ron#stagger_recover-o5",
            "dude/dude.trickfilm.ron#stagger_recover-o6",
            "dude/dude.trickfilm.ron#stagger_recover-o7",
            "dude/dude.trickfilm.ron#axe_kick-o0",
            "dude/dude.trickfilm.ron#axe_kick-o1",
            "dude/dude.trickfilm.ron#axe_kick-o2",
            "dude/dude.trickfilm.ron#axe_kick-o3",
            "dude/dude.trickfilm.ron#axe_kick-o4",
            "dude/dude.trickfilm.ron#axe_kick-o5",
            "dude/dude.trickfilm.ron#axe_kick-o6",
            "dude/dude.trickfilm.ron#axe_kick-o7",
            "dude/dude.trickfilm.ron#axe_kick_recover-o0",
            "dude/dude.trickfilm.ron#axe_kick_recover-o1",
            "dude/dude.trickfilm.ron#axe_kick_recover-o2",
            "dude/dude.trickfilm.ron#axe_kick_recover-o3",
            "dude/dude.trickfilm.ron#axe_kick_recover-o4",
            "dude/dude.trickfilm.ron#axe_kick_recover-o5",
            "dude/dude.trickfilm.ron#axe_kick_recover-o6",
            "dude/dude.trickfilm.ron#axe_kick_recover-o7",
            "dude/dude.trickfilm.ron#spinning_back_kick-o0",
            "dude/dude.trickfilm.ron#spinning_back_kick-o1",
            "dude/dude.trickfilm.ron#spinning_back_kick-o2",
            "dude/dude.trickfilm.ron#spinning_back_kick-o3",
            "dude/dude.trickfilm.ron#spinning_back_kick-o4",
            "dude/dude.trickfilm.ron#spinning_back_kick-o5",
            "dude/dude.trickfilm.ron#spinning_back_kick-o6",
            "dude/dude.trickfilm.ron#spinning_back_kick-o7",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o0",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o1",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o2",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o3",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o4",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o5",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o6",
            "dude/dude.trickfilm.ron#spinning_back_kick_recover-o7",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o0",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o1",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o2",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o3",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o4",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o5",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o6",
            "dude/dude.trickfilm.ron#spinning_heel_kick-o7",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o0",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o1",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o2",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o3",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o4",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o5",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o6",
            "dude/dude.trickfilm.ron#spinning_heel_kick_recover-o7",
            "dude/dude.trickfilm.ron#stance_broken-o0",
            "dude/dude.trickfilm.ron#stance_broken-o1",
            "dude/dude.trickfilm.ron#stance_broken-o2",
            "dude/dude.trickfilm.ron#stance_broken-o3",
            "dude/dude.trickfilm.ron#stance_broken-o4",
            "dude/dude.trickfilm.ron#stance_broken-o5",
            "dude/dude.trickfilm.ron#stance_broken-o6",
            "dude/dude.trickfilm.ron#stance_broken-o7",
            "dude/dude.trickfilm.ron#stance_broken_recover-o0",
            "dude/dude.trickfilm.ron#stance_broken_recover-o1",
            "dude/dude.trickfilm.ron#stance_broken_recover-o2",
            "dude/dude.trickfilm.ron#stance_broken_recover-o3",
            "dude/dude.trickfilm.ron#stance_broken_recover-o4",
            "dude/dude.trickfilm.ron#stance_broken_recover-o5",
            "dude/dude.trickfilm.ron#stance_broken_recover-o6",
            "dude/dude.trickfilm.ron#stance_broken_recover-o7",
            "dude/dude.trickfilm.ron#parry-o0",
            "dude/dude.trickfilm.ron#parry-o1",
            "dude/dude.trickfilm.ron#parry-o2",
            "dude/dude.trickfilm.ron#parry-o3",
            "dude/dude.trickfilm.ron#parry-o4",
            "dude/dude.trickfilm.ron#parry-o5",
            "dude/dude.trickfilm.ron#parry-o6",
            "dude/dude.trickfilm.ron#parry-o7",
            "dude/dude.trickfilm.ron#parry_fail-o0",
            "dude/dude.trickfilm.ron#parry_fail-o1",
            "dude/dude.trickfilm.ron#parry_fail-o2",
            "dude/dude.trickfilm.ron#parry_fail-o3",
            "dude/dude.trickfilm.ron#parry_fail-o4",
            "dude/dude.trickfilm.ron#parry_fail-o5",
            "dude/dude.trickfilm.ron#parry_fail-o6",
            "dude/dude.trickfilm.ron#parry_fail-o7",
            "dude/dude.trickfilm.ron#parry_success-o0",
            "dude/dude.trickfilm.ron#parry_success-o1",
            "dude/dude.trickfilm.ron#parry_success-o2",
            "dude/dude.trickfilm.ron#parry_success-o3",
            "dude/dude.trickfilm.ron#parry_success-o4",
            "dude/dude.trickfilm.ron#parry_success-o5",
            "dude/dude.trickfilm.ron#parry_success-o6",
            "dude/dude.trickfilm.ron#parry_success-o7",
            "dude/dude.trickfilm.ron#parry_success_recover-o0",
            "dude/dude.trickfilm.ron#parry_success_recover-o1",
            "dude/dude.trickfilm.ron#parry_success_recover-o2",
            "dude/dude.trickfilm.ron#parry_success_recover-o3",
            "dude/dude.trickfilm.ron#parry_success_recover-o4",
            "dude/dude.trickfilm.ron#parry_success_recover-o5",
            "dude/dude.trickfilm.ron#parry_success_recover-o6",
            "dude/dude.trickfilm.ron#parry_success_recover-o7",
            "dude/dude.trickfilm.ron#slide-o0",
            "dude/dude.trickfilm.ron#slide-o1",
            "dude/dude.trickfilm.ron#slide-o2",
            "dude/dude.trickfilm.ron#slide-o3",
            "dude/dude.trickfilm.ron#slide-o4",
            "dude/dude.trickfilm.ron#slide-o5",
            "dude/dude.trickfilm.ron#slide-o6",
            "dude/dude.trickfilm.ron#slide-o7",
            "dude/dude.trickfilm.ron#slide_recover-o0",
            "dude/dude.trickfilm.ron#slide_recover-o1",
            "dude/dude.trickfilm.ron#slide_recover-o2",
            "dude/dude.trickfilm.ron#slide_recover-o3",
            "dude/dude.trickfilm.ron#slide_recover-o4",
            "dude/dude.trickfilm.ron#slide_recover-o5",
            "dude/dude.trickfilm.ron#slide_recover-o6",
            "dude/dude.trickfilm.ron#slide_recover-o7",
            "dude/dude.trickfilm.ron#jump-o0",
            "dude/dude.trickfilm.ron#jump-o1",
            "dude/dude.trickfilm.ron#jump-o2",
            "dude/dude.trickfilm.ron#jump-o3",
            "dude/dude.trickfilm.ron#jump-o4",
            "dude/dude.trickfilm.ron#jump-o5",
            "dude/dude.trickfilm.ron#jump-o6",
            "dude/dude.trickfilm.ron#jump-o7",
            "dude/dude.trickfilm.ron#jump_recover_idle-o0",
            "dude/dude.trickfilm.ron#jump_recover_idle-o1",
            "dude/dude.trickfilm.ron#jump_recover_idle-o2",
            "dude/dude.trickfilm.ron#jump_recover_idle-o3",
            "dude/dude.trickfilm.ron#jump_recover_idle-o4",
            "dude/dude.trickfilm.ron#jump_recover_idle-o5",
            "dude/dude.trickfilm.ron#jump_recover_idle-o6",
            "dude/dude.trickfilm.ron#jump_recover_idle-o7",
            "dude/dude.trickfilm.ron#jump_recover_moving-o0",
            "dude/dude.trickfilm.ron#jump_recover_moving-o1",
            "dude/dude.trickfilm.ron#jump_recover_moving-o2",
            "dude/dude.trickfilm.ron#jump_recover_moving-o3",
            "dude/dude.trickfilm.ron#jump_recover_moving-o4",
            "dude/dude.trickfilm.ron#jump_recover_moving-o5",
            "dude/dude.trickfilm.ron#jump_recover_moving-o6",
            "dude/dude.trickfilm.ron#jump_recover_moving-o7",
            "dude/dude.trickfilm.ron#fall-o0",
            "dude/dude.trickfilm.ron#fall-o1",
            "dude/dude.trickfilm.ron#fall-o2",
            "dude/dude.trickfilm.ron#fall-o3",
            "dude/dude.trickfilm.ron#fall-o4",
            "dude/dude.trickfilm.ron#fall-o5",
            "dude/dude.trickfilm.ron#fall-o6",
            "dude/dude.trickfilm.ron#fall-o7",
            "dude/dude.trickfilm.ron#fall_recover-o0",
            "dude/dude.trickfilm.ron#fall_recover-o1",
            "dude/dude.trickfilm.ron#fall_recover-o2",
            "dude/dude.trickfilm.ron#fall_recover-o3",
            "dude/dude.trickfilm.ron#fall_recover-o4",
            "dude/dude.trickfilm.ron#fall_recover-o5",
            "dude/dude.trickfilm.ron#fall_recover-o6",
            "dude/dude.trickfilm.ron#fall_recover-o7",
            "dude/dude.trickfilm.ron#dropkick-o0",
            "dude/dude.trickfilm.ron#dropkick-o1",
            "dude/dude.trickfilm.ron#dropkick-o2",
            "dude/dude.trickfilm.ron#dropkick-o3",
            "dude/dude.trickfilm.ron#dropkick-o4",
            "dude/dude.trickfilm.ron#dropkick-o5",
            "dude/dude.trickfilm.ron#dropkick-o6",
            "dude/dude.trickfilm.ron#dropkick-o7",
            "dude/dude.trickfilm.ron#dropkick_recover-o0",
            "dude/dude.trickfilm.ron#dropkick_recover-o1",
            "dude/dude.trickfilm.ron#dropkick_recover-o2",
            "dude/dude.trickfilm.ron#dropkick_recover-o3",
            "dude/dude.trickfilm.ron#dropkick_recover-o4",
            "dude/dude.trickfilm.ron#dropkick_recover-o5",
            "dude/dude.trickfilm.ron#dropkick_recover-o6",
            "dude/dude.trickfilm.ron#dropkick_recover-o7",
            "dude/dude.trickfilm.ron#kneekick-o0",
            "dude/dude.trickfilm.ron#kneekick-o1",
            "dude/dude.trickfilm.ron#kneekick-o2",
            "dude/dude.trickfilm.ron#kneekick-o3",
            "dude/dude.trickfilm.ron#kneekick-o4",
            "dude/dude.trickfilm.ron#kneekick-o5",
            "dude/dude.trickfilm.ron#kneekick-o6",
            "dude/dude.trickfilm.ron#kneekick-o7",
            "dude/dude.trickfilm.ron#kneekick_recover-o0",
            "dude/dude.trickfilm.ron#kneekick_recover-o1",
            "dude/dude.trickfilm.ron#kneekick_recover-o2",
            "dude/dude.trickfilm.ron#kneekick_recover-o3",
            "dude/dude.trickfilm.ron#kneekick_recover-o4",
            "dude/dude.trickfilm.ron#kneekick_recover-o5",
            "dude/dude.trickfilm.ron#kneekick_recover-o6",
            "dude/dude.trickfilm.ron#kneekick_recover-o7",
        ),
        collection(typed)
    )]
    pub dude_animations: Vec<Handle<AnimationClip2D>>,

    // --- MAP ---
    #[asset(path = "map/map.ldtk")]
    pub map: Handle<LdtkProject>,

    // --- FONTS ---
    #[asset(path = "fonts/PressStart2P.ttf")]
    pub pixel_font: Handle<Font>,
}
